library(pathview)
#xenobiotics degradation and metabolism
pv.out_xy_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00622", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_tol_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00623", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_nap_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00626", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_eb_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00642", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_benzoate_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00362", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_styrene_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00643", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_fb_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00364", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_aro_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "01220", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_dio_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00621", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_ap_met <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00440", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_ca_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00625", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_nt_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00633", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_PAH_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00624", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_P450 <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00980", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_DDT_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00351", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_cch_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00361", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_ab_deg <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00627", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)

#lipids
pv.out_fa_bio <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00061", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_ufa_bio <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "01040", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_glu <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00010", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_pent <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00030", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_GPL <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00564", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pv.out_GL <- pathview(cpd.data = KEGG_int_for_pathview_matrix[, 1:ncol(KEGG_int_for_pathview_matrix)], pathway.id = "00561", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
