library(pathview)
#xenobiotics degradation and metabolism
pv.out_xy_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00622", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
xy_deg <- merge(pv.out_xy_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_tol_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00623", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
tol_deg <- merge(pv.out_tol_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_nap_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00626", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
nap_deg <- merge(pv.out_nap_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_eb_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00642", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
eb_deg <- merge(pv.out_eb_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_benzoate_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00362", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
benzoate_deg <- merge(pv.out_benzoate_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_styrene_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00643", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
styrene_deg <- merge(pv.out_styrene_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_fb_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00364", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
fb_deg <- merge(pv.out_fb_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_aro_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "01220", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
aro_deg <- merge(pv.out_aro_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_dio_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00621", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
dio_deg <- merge(pv.out_dio_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_ap_met <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00440", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
ap_met <- merge(pv.out_ap_met$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_ca_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00625", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
ca_deg <- merge(pv.out_ca_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_nt_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00633", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
nt_deg <- merge(pv.out_nt_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_PAH_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00624", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
PAH_deg <- merge(pv.out_PAH_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_P450 <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00980", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
P450_deg <- merge(pv.out_P450$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_DDT_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00351", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
DDT_deg <- merge(pv.out_DDT_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_cch_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00361", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
cch_deg <- merge(pv.out_cch_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_ab_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00627", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
ab_deg <- merge(pv.out_ab_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_at_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00791", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
at_deg <- merge(pv.out_at_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")


save(list=ls(all=TRUE), file="pathview-out.RData")

#lipids
pv.out_fa_bio <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00061", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
fa_bio <- merge(pv.out_fa_bio$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_ufa_bio <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "01040", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
ufa_bio <- merge(pv.out_ufa_bio$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_glu <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00010", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
glu <- merge(pv.out_glu$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_pent <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00030", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
pent <- merge(pv.out_pent$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_GPL <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00564", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
GPL <- merge(pv.out_GPL$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_GL <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00561", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T)
GL <- merge(pv.out_GL$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")

#amino acid
pv.out_alanine <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00250", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
alanine <- merge(pv.out_alanine$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_glycine <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00260", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
glycine <- merge(pv.out_glycine$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_cysteine <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00270", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
cysteine <- merge(pv.out_cysteine$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_val_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00280", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
val_deg <- merge(pv.out_val_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_val_bio <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00290", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
val_bio <- merge(pv.out_val_bio$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_lysine_bio <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00300", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
lysine_bio <- merge(pv.out_lysine_bio$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_lysine_deg <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00310", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
lysine_deg <- merge(pv.out_lysine_deg$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_arginine_bio <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00220", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
arginine_bio <- merge(pv.out_arginine_bio$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_arginine_met <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00330", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
arginine_met <- merge(pv.out_arginine_met$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_histidine <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00340", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
histidine <- merge(pv.out_histidine$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_tyrosine <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00350", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
tyrosine <- merge(pv.out_tyrosine$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_phenylalanine_met <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00360", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
phenylalanine_met <- merge(pv.out_phenylalanine_met$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_tryptophan <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00380", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
tryptophan <- merge(pv.out_tryptophan$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")
pv.out_phenylalanine_bio <- pathview(cpd.data = pv_matrix[, 1:ncol(pv_matrix)], pathway.id = "00400", species = "ko", keys.align = "y", kegg.native = T, match.data = F, multi.state = T, same.layer = T, new.signature = F)
phenylalanine_bio <- merge(pv.out_phenylalanine_bio$plot.data.cpd, pathview1, by.x = "kegg.names", by.y = "KEGG.ID")